<?php


namespace App\Services;


use App\Repositories\AppRepository;
use App\Repositories\UserRepository;

class UserService extends ApiService
{

public function __construct(UserRepository $repository)
{
    parent::__construct($repository);
}
public function store($request)
{
   // return parent::store($request); // TODO: Change the autogenerated stub
    $user=$this->repository->model->create($request->all()->except(['roles']));
    $user->roles()->attach($request->all()->only(['roles']));
    return $this->responseSuccesfully($user->roles,201);

}
}
